version: '3'
services:

    mysql:
        container_name: mysql
        restart: always
        image: hypriot/rpi-mysql:latest
        volumes:
            - '/home/pi/blog/data:/var/lib/mysql'
        env_file:
            - env/mysql.env
        ports:
            - 3306:3306
        networks:
            - app-network

    redis:    
        container_name: redis
        image: redis:latest
        restart: always
        networks:
            - app-network
    pma:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        env_file:
            - env/mysql.env
        ports:
            - 8081:5600
        links:
            - db:db
        networks:
            - app-network  

    wordpress:
        depends_on:
            - mysql
            - redis
        container_name: wordpress
        image: wordpress:latest
        restart: always        
        ports:
            - 80:80
            - 443:443
        volumes:
            - '/homdocker oe/pi/blog/html:/var/www/html'
        env_file:
            - env/blog.env
        networks:
            - app-network            

volumes:
    mysql: null
    wordpress: null
    nginx: null

networks:
    app-network:
        driver: bridge