version: '3'
services:

    wordpress:
        container_name: wordpress
        build: ./wordpress-docker
        restart: always
        env_file:
            - env/blog.env
        volumes:
            - ./wordpress:/var/www/html

    nginx:
        depends_on:
            - wordpress
        container_name: nginx
        build: ./nginx-docker
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./wordpress:/var/www/html

volumes:
    wordpress:
    nginx: