version: '3'
services:

    mysql:
        container_name: mysql
        restart: always
        image: hypriot/rpi-mysql:latest
        volumes:
            - '/home/pi/blog/data:/var/lib/mysql'
        env_file:
            - env/mysql.env
        networks:
            - app-network

    redis:    
        container_name: redis
        image: redis:latest
        restart: always
        networks:
            - app-network

    wordpress:
        depends_on:
            - mysql
            - redis
        container_name: wordpress
        image: wordpress:latest
        restart: always        
        ports:
            - 80:80
        volumes:
            - '/homdocker oe/pi/blog/html:/var/www/html'
        env_file:
            - env/blog.env
        networks:
            - app-network            

volumes:
    mysql: null
    wordpress: null
    nginx: null

networks:
  app-network:
    driver: bridge