version: '3'
services:

    wordpress:
        container_name: wordpress
        image: wordpress:5.1.1-fpm-alpine
        restart: always
        env_file:
            - env/blog.env
        volumes:
            - ./wordpress:/var/www/html

    nginx:
        depends_on:
            - wordpress
        container_name: nginx
        image: nginx:stable-alpine
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./wordpress:/var/www/html

volumes:
    wordpress:
    nginx:
